[package]
name = "habctl"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/davidkern/habctl"
description = "HAB truck camper backend services."

[dependencies]
async-std = { version = "1.7.0", features = ["attributes"]}
async-trait = "0.1.42"
tide = "0.15.0"
