[package]
name = "habctl"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/davidkern/habctl"
description = "HAB truck camper backend services."

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.0", features = ["serde"] }
futures = "0.3.8"
log = "0.4.11"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.118", features = ["derive"] }
# NOTE: blocked upgrading to tokio 0.3 by warp
tokio = { version = "0.2.23", features = ["full"] }
warp = "0.2.5"
