[package]
name = "habctl"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/davidkern/habctl"
description = "HAB truck camper backend services."

[dependencies]
tokio = { version = "0.3.5", features = ["full"] }
tokio-compat-02 = "0.1.2"
warp = "0.2.5"
