#!/bin/sh
socat tcp-l:13401,reuseaddr,fork file:/dev/serial/by-id/usb-VictronEnergy_BV_VE_Direct_cable_VE47E73U-if00-port0,nonblock,waitlock=/var/run/usb-VictronEnergy_BV_VE_Direct_cable_VE47E73U-if00-port0.lock
